services:
  order:
    container_name: ${ORDER_NAME}
    build:
      context: ../ecommerce
      dockerfile: order-service/Dockerfile
      target: run
    restart: always
    depends_on:
      order_db:
        condition: service_healthy
    expose:
      - "${GRPC_PORT}"
    environment:
      GRPC_PORT: ${GRPC_PORT}
      DB_HOST: order_db
      DB_NAME: shop_orders
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      LOG_LEVEL: ${LOG_LEVEL}
    networks:
      - ecommerce_net
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:${GRPC_PORT}"]
      start_period: 5s
      interval: 10s
      timeout: 3s
      retries: 10
    profiles: ["run"]

  order_db:
    image: mariadb:latest
    restart: always
    expose:
      - "${DB_PORT}"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../ecommerce/order-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - order_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 60s
      start_interval: 10s
      interval: 60s
      timeout: 15s
      retries: 10
    networks:
      - ecommerce_net
    profiles: ["run"]

# TEST

  order_test:
    container_name: ${ORDER_NAME}_test
    build:
      context: ../ecommerce
      dockerfile: order-service/Dockerfile
      target: test
    depends_on:
      order_test_db:
        condition: service_healthy
    expose:
      - "${GRPC_PORT}"
    environment:
      GRPC_PORT: ${GRPC_PORT}
      DB_HOST: order_test_db
      DB_NAME: shop_orders
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      LOG_LEVEL: ${LOG_LEVEL}
    networks:
      - test_net
    profiles: ["test"]

  order_test_db:
    image: mariadb:latest
    restart: always
    expose:
      - "${DB_PORT}"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../ecommerce/order-service/db/initTest.sql:/docker-entrypoint-initdb.d/init.sql
      - order_test_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 60s
      start_interval: 10s
      interval: 60s
      timeout: 15s
      retries: 10
    networks:
      - test_net
    attach: false
    profiles: ["test"]

networks:
  ecommerce_net:
    name: ecommerce_net
  test_net:
    name: test_net

volumes:
  order_db:
  order_test_db:
