DROP DATABASE IF EXISTS Auth;
CREATE DATABASE Auth;
USE Auth;

DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    Username VARCHAR(32) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Email VARCHAR(64) NOT NULL UNIQUE,
    Phone VARCHAR(20)
) ENGINE=InnoDB;